version: 2.1

executors:
  mac-executor:
    macos:
      xcode: "14.1.0"
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: mac-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # Install nvm (Node Version Manager)
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
            # Source nvm to make it available in the shell
            source ~/.nvm/nvm.sh
            # Install the desired Node.js version (e.g., 16)
            nvm install 12.22.12
            # Set the default node version
            nvm use 12
            # Verify the Node.js version
            node -v
      - run:
          name: Install dependencies
          command: npm ci

  deploy:
    executor: mac-executor
    environment:
      CIRCLE_OS: macos
    steps:
      - checkout
      - run:
          name: Run deploy script
          command: bash deploy.circleci.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_dependencies
      - deploy:
          requires:
            - install_dependencies

caches:
  dependencies: ~/.cache/yarn
  electron_cache: ~/.cache/electron
  electron_builder_cache: ~/.cache/electron-builder