version: 2.1

executors:
  mac-executor:
    macos:
      xcode: "14.1.0"
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: mac-executor
    steps:
      - checkout
      - run:
          name: Install Node.js using nvm
          command: |
            # Install nvm (Node Version Manager)
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
            # Source nvm to make it available in the shell
            source ~/.nvm/nvm.sh
            # Install the desired Node.js version (e.g., 16)
            nvm install 18
            # Set the default node version
            nvm use 18
            # Verify the Node.js version
            node -v
            npm ci
            npm run release
      - store_artifacts:
          path: dist/JenkinsMonitor-0.0.8.dmg  # Path to your .dmg file
          destination: dmg-artifacts      

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_dependencies

caches:
  dependencies: ~/.cache/yarn
  electron_cache: ~/.cache/electron
  electron_builder_cache: ~/.cache/electron-builder