version: 2.1

executors:
  mac-executor:
    macos:
      xcode: "10.2.0"
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: mac-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install

  deploy:
    executor: mac-executor
    environment:
      CIRCLE_OS: macos
    steps:
      - checkout
      - run:
          name: Run deploy script
          command: bash deploy.circleci.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_dependencies
      - deploy:
          requires:
            - install_dependencies

caches:
  dependencies: ~/.cache/yarn
  electron_cache: ~/.cache/electron
  electron_builder_cache: ~/.cache/electron-builder