version: 2.1
jobs:
  build:
    macos:
      xcode: 11.6.2 # indicate your selected version of Xcode
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Generate Builds
          command: npm run release --mac

      - store_artifacts:
          path: ~/repo/out/make