version: 2.1
jobs:
  build:
    macos:
      xcode: 10.3.0 # indicate your selected version of Xcode
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Fix Bug in NPM
          command: "sudo chown -R 501:20 \"/Users/distiller/.npm\""
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Generate Builds
          command: npm run release --mac
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=0.0.8
            ghr -t "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" -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./dist/        
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build